### ISSUE TITLE
rings e pulseiras e beblack categorias

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#1]
olá 

as categorias do 
silicone (categoria_be_splash_nova.php)
metal (categoria_be_steel_nova.php)
loop  (categoria_loop_nova.php)
encontrei vi que tem erros, porém estão funcionando sem estar com o layout desconfigurado.

preciso arrumar os erros das categorias: rings / pulseiras / beblack

você sabe me informar se é padrão as 3?
você pode me dizer onde consigo encontrá-las?

não sei se foi você ou outro programador que as criou, mas se puder me ajudar, agradeço.

obrigado

**Comment by diogenesjup** [comment]
Olá bom dia
É possível que existam erros, principalmente no front-end na relação com o JavaScript, por causa de alguns códigos inseridos por outro programador. As categorias rings, pulseiras e beblack na ocasião em que escrevi essa documentação tinham seus próprios arquivos de configuração (igual é o silicone, metal, loop etc). Rings e Pulseiras eram em um único arquivo, e o beblack em um arquivo especifico para ele. Caso eles não estejam mais ai, ao meu ver o melhor direcionamento (assumindo que está fazendo uma manutenção/alteração no ambiente atual) é seguir essa estratégia de cada tipo de produto ter seu próprio arquivo. Agora, se por acaso estiver refazendo todo o ambiente, dai é melhor fazer o padrão recomendado para theming woocommerce.

**Comment by beprogram** [comment]
´´As categorias rings, pulseiras e beblack na ocasião em que escrevi essa documentação tinham seus próprios arquivos de configuração´´
provavelmente vc tem um backup disso, acredito, aqui em todos os backups antigos não encontrei esses arquivos.
quais seriam os nomes que vc colocou pra eles?

**Comment by diogenesjup** [comment]
Eu vejo que em uma das minhas cópia de 2019 que no diretório "modelos-produtos/" temos os arquivos
pulseiras.php e rings.php (nomes auto explicativos).
Agora apenas em uma cópia de 2020 encontrei no mesmo diretório o arquivo beblack.php assim como outros semelhantes como o benight.php

basicamente todos os tipos de produtos deveriam estar dentro desse diretório wp-content/themes/bewatch-wordpress/modelo-produtos

Isso se, a estrutura do tema foi mantida, ninguém tiver apagado/removido etc

**Comment by beprogram** [comment]
entendi diogenes. de repente eu quem não consegui me expressar.

notei que você criou o modelo do produto e também consegui entender o que você pontuou na explicação, principalmente pelo fato de que, cada modelo de produto você criou um arquivo. joia, excelente!! ficou bem pontuado.

o que eu realmente não estou entendendo. é sobre o layout das categorias, pois o besplash, beloop e besteel. estão em um formato a qual vc indica que foi feito por outro programador, inclusive.

mas o beblack, pulseiras e rings eu não encontro onde está vinculado o layout das categorias. por exemplo:
dentro do beloop por exemplo tem subcategorias geek, mandalas... só que não aparece no beblack.

se você acessar o beblack talvez fique em branco pois está como privado os produtos.
mas eles ficam de forma corrida. como se não tivesse layout algum, diferente do besteel,besplash e o beloop...
acredito que você tenha feito algum layout de categorias, até pela estrutura do site estar bem completa.

você pode me ajudar a entender essa parte de layout dessas categorias principais?
ou como eu faço para editar essas da pulseira/beblack/rings;;;  sem prejudicar a estrutura
ficou confuso para mim. se puder agradeço.

achei melhor falar com você antes, para mantermos o projeto sem nenhum eventual problema.

grato

**Comment by beprogram** [comment]
pois eu vi aqui que tanto na woo-categoria e woo-categoria-pai estao linkando com essas novas paginas. 
silicone (categoria_be_splash_nova.php)
metal (categoria_be_steel_nova.php)
loop (categoria_loop_nova.php)

mas não encontrei do beblack por exemplo.

e encontrei o besteel e o besplash na pai e o beloop na categoria apenas.
não seguiu a mesma ordem.

se você puder me dar esse feedback seu, estou meio confuso.

**Comment by diogenesjup** [comment]
Ah agora entendi sua dúvida,
você quer saber sobre as categorias do tipo "archive". Teoricamente eram para estar todas independente do tipo dentro do woo-categorias.php e suas página respectivas (woo pai e woo filha). Esses arquivos final "_nova.php" foi outra pessoa que montou e o cenário que me passaram sobre isso era que eles precisam editar a página da listagem editando diretamente o código (sem usar o loop default), inclusive se não me engano esses arquivos final "_nova.php" estão apenas com o front que eles editavam manualmente ao invés de puxar pelo painel usando wp_query ou coisa do tipo.

Eu não sei exatamente o que está fazendo, mas me parece um caminho melhor usar o template padrão do woo-categorias e apenas adicionar uma nova conditional tag para a categoria nova, do que usar esses arquivos "_nova.php" que se ainda estiverem igual as minhas cópias tem apenas um front de uma forma meio sem noção já que não é construida usando o padrao do WP

**Comment by beprogram** [comment]
pois é ta bem confuso esse ´´nova´´ to meio perdido com esses arquivos 
pq foi feito meio que umas junçoes bem diferentes.

pq eu acho que ele apagou as categorias, no que voce criou o beblack ele acabou fincando sem nenhuma categoria.
nao sei se vc entende o que estou falando...

vou precisar por o beblack, pulseiras e rings nas categorias, só que ele apagou o teu arquivo
ai to pensando no que fazer juntar as duas vai ser complexo.... e provavelmente vai dar uma explosão. rsrs
estou preocpado

ele criou um arquivo novo desse woo categorias que ta chamando só as que ele fez como ´´nova´´

**Comment by diogenesjup** [comment]
É eu também acho que vai dar uma "explosão" kkk
o ideal era esse tema ser refeito, por que cada um que coloca a mão nele acaba remendando um novo pedaço para nao dar problema nos remendos passados.

**Comment by beprogram** [comment]
Sim explosão nuclear, com certeza.. rsrs

 eu vou deixar só pra elas usarem agora final de ano, pra não explodir agora na época de vendas.
e vou refazer esse tema e botar a casa em ordem, ta bem caótico. esses remendos desses caras.

mas fechou então;
obrigado pela ajuda 0/

**Comment by beprogram** [comment]
bom dia tudo bom?
pelo o que vi aqui com as meninas a ultima home veio com um bug.
 os ícones abaixo do banner e as setas do banner estão ficando por cima do menu mobile.
por acaso você tem o arquivo corrigido para eu subir aqui?

obrigado 👍

**Comment by diogenesjup** [comment]
Bom dia!
Não sei se tenho esses arquivos, mas é só alterar a propriedade z-index no CSS.
Ou diminuir o zindex dos icones e setas para um valor menor que o do menu mobile, ou aumentar o zindex do menu mobile para um valor maior que os ícones e setas

Abraços

**Comment by beprogram** [comment]
obrigado pelo retorno.
tudo bem posso arrumar aqui sem problemas.
o único problema, na verdade, é que não estou encontrando essas setas, e o carrossel abaixo do banner, nem por menos o z-index deles. no style (css)


o slide principal, no style (css) por exemplo está com o z-index de 400. vc sabe me dizer se está junto com a seta?
pelo o que testei acredito que não. aumentei o mobile baseado nele e não sobe.
em todo o resto do site o mobile funciona certinho, mas na home não estou conseguindo encontrar.

eu de cara, quando vi fui atrás já imaginando ser o z-index. o problema é que não consegui encontrar as setas e o carrosel abaixo do banner ( que tem aqueles icones)

como você fez a home deve lembrar melhor de onde posso ir para posicionar.
você pode dar uma mão nesse bug?
 
obrigado 
bom trabalho

**Comment by diogenesjup** [comment]
Se eu não me engano seria na classe .controle-produtos-na-homepage 

`
.controle-produtos-na-homepage .owl-theme .custom-nav-produtos .owl-prev,
.controle-produtos-na-homepage .owl-theme .custom-nav-produtos .owl-next {
  position: absolute;
  height: 100px;
  color: inherit;
  background: none;
  border: none;
  z-index: 92;
  outline: none !important;
}

`

para localizar os controles da navegação dos carrosseis da página, no HTML procure sempre pelos "owl-controls" por que ai vai dar para saber qual a classe pai para setar o z-index


Talvez seja mais fácil atribuir um z-index:9999999999 para o container do menu mobile

**Comment by beprogram** [comment]
você pode me confirmar qual é o container  do mobile?

coloquei um z index alto

#menuMobile{
    position: fixed;
    /* display: none; */
    top:0;
    left: 0;
    width: 100%;
    height: 100%;
    overflow-y: scroll;
    background: #fff;
    line-height: 2.2em;
    padding: 16px;
    padding-bottom: 100px;
    z-index: 9999999999; !important;
    cursor: pointer;


mas cara to encabulado me ajuda a entender esse enigma.
pois o banner esta certo,parece que a seta e esse segundo bloco abaixo do banner principal estão desconectados.
parece o que o problema ta no carrossel mas eles estão abaixo do mobile, parece estar certinho.

to quebrando a cabeça aqui

**Comment by diogenesjup** [comment]
Eu não consigo te dizer exatamente, por que no site da Bew é bloqueado o
CTRL direito do mouse para eu inspecionar, dai como eu não fiz esse menu
mobile ai, não sei te dizer exatamente,

No código que me mandou tem um erro de sintaxe (em negrito)

#menuMobile{
position: fixed;
/* display: none; */
top:0;
left: 0;
width: 100%;
height: 100%;
overflow-y: scroll;
background: #fff;
line-height: 2.2em;
padding: 16px;
padding-bottom: 100px;
*z-index: 9999999999; !important;*
cursor: pointer;

Repara que tem dois pontos e virgula, o correto seria

z-index: 9999999999 !important;

Qualquer coisa habilita o CTRL direito do mouse do site da Bew para eu
conseguir inspecionar e te ajudar melhor

Em qui., 15 de out. de 2020 às 15:50, beprogram <notifications@github.com>
escreveu:

**Comment by beprogram** [comment]
corrigi o z-index: 9999999999 !important;

ta habilitado xD

**Comment by beprogram** [comment]
já habilitei aqui para voce dar uma olhada na inspeção 
com o botao direito 👍

**Comment by diogenesjup** [comment]
Da uma olhada nesse vídeo
https://youtu.be/5ocAb9qtLC0
Isso vai resolver a questão

Em qui., 15 de out. de 2020 às 17:47, beprogram <notifications@github.com>
escreveu:

**Comment by beprogram** [comment]
aí sim!!! você é fera demais!!!!
já coloquei pra cima =]

obrigado ajudou muito
