### ISSUE TITLE
Bug Central de ajuda 

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#14]
na central de ajuda - pagamento e reembolso :
 nao esta sendo possivel abrir os sub textos
segue imagem:
![Central](https://user-images.githubusercontent.com/71886392/121590860-3526fd80-ca0f-11eb-84b5-9c41669e50c7.jpg)

**Comment by beprogram** [comment]
dentro no painel - na parte central de ajuda 
preciso ter autonomia para arrastar as perguntas - trocar de posição livremente inverter a 1 pela 3 e assim sucessivamente.
![Central](https://user-images.githubusercontent.com/71886392/121591595-11b08280-ca10-11eb-9ab7-1e3c643972dc.jpg)

**Comment by beprogram** [comment]
campos muito pequenos para digitar as sub perguntas, preciso de campo como o de perguntas e respostas - maiores 
![Central](https://user-images.githubusercontent.com/71886392/121591925-7370ec80-ca10-11eb-9320-ecf7527dbc0d.jpg)

**Comment by beprogram** [comment]
xml do instagrammmm!!!

**Comment by diogenesjup** [comment]
Consegui finalmente resolver esse problema,
a questão é que a primeira pergunta, náo pode ter sub perguntas. Dai eu criei uma pergunta teste lá no grupo "Pagamentos e Reembolsos" dai funcionou. Dai editem para um texto real, e ai sigam essa regra: a primeira pergunta nunca pode ter sub perguntas, só as demais.
