### ISSUE TITLE
hackeado

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#2]
boa tarde
diogenes nao te pertubaria se o assunto n fosse sério
mas a unica pessoa que eu tenho certeza que pode me ajudaré voce
e pago sem problemas

o site foi hackeado voce pode me ajudar
tenho acesso a tudo 
menos ao wordpress

grata
roberta

**Comment by diogenesjup** [comment]
Como ja estamos falando por canal, vou colocar esse aqui como concluído
