### ISSUE TITLE
link nao seguro 

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#21]
alguns links internos aparece nao seguro - analisar corrigir para nao aconter 
![Central 2](https://user-images.githubusercontent.com/71886392/121922578-7b7ea400-cd10-11eb-8b43-2c3ad51b3602.JPG)

**Comment by diogenesjup** [comment]
Como falei no audio do WhatsApp, não vou atuar em itens do site atual da Bew, focando apenas no site novo. Porém, comentei sobre o que pode ser
