### ISSUE TITLE
itens correção dúvida (segunda) 14/06

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#22]
https://homologacao.servidorseguro.cloud/wp-admin/post.php?post=930&action=edit
nesse produto que to editando eu nao selecionei fonte na lateral mas ta puxando sozinho

mostrar os contornos das fontes

monstrar os grupos personalizados

esse aqui nao entendi pq repete? 
![Captura de Tela 2021-06-14 às 15 04 20](https://user-images.githubusercontent.com/71886392/121939447-6b23f480-cd23-11eb-8b1e-623a094614d4.png)

essa fonte a shorelines eu preciso colocar ela mas ela so tem no dafonthttps://www.dafont.com/pt/shorelines-script.font
que se tu escreve com a palavra assim (roberta) ela puxa aquelas linhas em qlqr letra, preciso!!!!

aqui nao estamos conseguindo fazer daquela forma que conversamos
para por de forma geral tb tipo promocoes e etc
![Captura de Tela 2021-06-14 às 15 30 30](https://user-images.githubusercontent.com/71886392/121941400-9a3b6580-cd25-11eb-9afd-2ab25ba2f315.png)

aqui na parte de grupo dos textos [ que fica abaixo do produto ] descrição do produto
habilitar para não ser uma imagem só que eu possa ir colocando a quantidade de imagens que eu quiser
bem como gif e videos
![Captura de Tela 2021-06-14 às 15 48 00](https://user-images.githubusercontent.com/71886392/121943518-0b7c1800-cd28-11eb-9e29-474436839ec6.png)

**Comment by diogenesjup** [comment]
Eu renomeei esse item para ficar mais claro o que tem dentro dele
