### ISSUE TITLE
produto simples 1 bug

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#29]
Oie
cadastramos o primeiro simples a [embalagem be box wood](https://homologacao.servidorseguro.cloud/produto/embalagem-be-box-wood/#)

porém duas coisas nao deram certo:

**1)** Diminuir o tamanho do mínimo da caixa da descrição e se aumentar a caixa aumenta

**2)** os icones ficaram em f fila nao era assim...
![Captura de Tela 2021-06-17 às 15 36 05](https://user-images.githubusercontent.com/71886392/122454441-c5ba8c00-cf81-11eb-996a-1e0e21883ee9.png)

**Comment by beprogram** [comment]
![Captura de Tela 2021-06-17 às 15 51 42](https://user-images.githubusercontent.com/71886392/122456539-13d08f00-cf84-11eb-8a00-54b02d123e1c.png)

**Comment by beprogram** [comment]
na verdade quando tivemos nossa call, eu acreditei que tinha explicado a maneira como precisávamos, porem não esta aplicado o que precisamos.

o produto simples - sao para produtos com edições limitadas, mas que possuem variação de estampa ou pulseira ou algo.....
por isso precisamos que o item tenha opção para escolher a estampa

no dia eu entendi que carrossel era a função, mas  nao é bem isso

aqui esta o link do mercado livre com essa opocao que precisamos, pode ser conversado e adaptado. mas serve para voce entender a necessidade.


https://produto.mercadolivre.com.br/MLB-1648418125-relogio-infantil-feminino-qq-menina-prova-d-agua-barato-_JM?searchVariation=63373324968#searchVariation=63373324968&position=7&search_layout=stack&type=item&tracking_id=c851cb36-200e-4e8c-87f1-ca0712b013ce

![image](https://user-images.githubusercontent.com/71886392/122457678-48911600-cf85-11eb-9e2e-bb635b04c0c3.png)

ao clicar no produto troca e pode comprar o selecionado. conseguiu entender?

**Comment by beprogram** [comment]
segue como tem que ficar 
![Captura de Tela 2021-06-23 às 09 57 31](https://user-images.githubusercontent.com/71886392/123105901-8e7b2d80-d40e-11eb-9e75-be095ced70c9.png)


explicacao:

as imagens da lateral servem pra pessoa escolher a variaçao daquele produto ( tipo a cor ) e ja visualizar pq troca a imagem quando clica no quadrado e tb troca o tipo escolhido.

1 indicar para o cliente a ação
2 posso por quantaas eu quiser
3 Tipo Escolhido: ( ai vem o modelo de uma das imagens que ta na lateral)

![06-23 às 09 57 31](https://user-images.githubusercontent.com/71886392/123106071-b5d1fa80-d40e-11eb-841f-400a06ad2bef.png)

**Comment by diogenesjup** [comment]
Sobre o problema do produto simple (texto e ícones)
https://youtu.be/DDDdGC5gIrg
