### ISSUE TITLE
Erro ao estabelecer uma conexão com o banco de dados

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#3]
nosso site esta dando isso Erro ao estabelecer uma conexão com o banco de dados
te mandei whats mas estou enviando aqui conforme vc pediu, acredito que facilita para ti.

você sabe me dizer como arrumar isso?
ou você pode arrumar, me passa o valor que já transfiro pra ti.

obrigada

**Comment by diogenesjup** [comment]
Problema resolvido! :)
