### ISSUE TITLE
RODAPE UM ERRINHO SIMPLES

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#30]

**Comment by beprogram** [comment]
SOBRE O BEWATCH EM CIMA DO COPYRIGHT

 A IMAGEM QUE EU SUBI É BEM GRANDE 
MAS LA NO RODAPE PARECE QUE TA BORRADO... PODE CORRIGIR?
E SE EU SUBO SVG SO DA DE LER COM LUPA KKK

![Captura de Tela 2021-06-17 às 17 23 22](https://user-images.githubusercontent.com/71886392/122467420-dde5d780-cf90-11eb-9b87-2f83fd166efe.png)

**Comment by diogenesjup** [comment]
Atualmente para mim a imagem está boa
http://bewatch.local/wp-content/uploads/2021/06/selos-pague.png

Se você subir um SVG, para ficar com boa resolução, a parte do texto, vocë precisa vetoriza-lo (ao invés de salvar apenas com a ferramenta de texto normal do photoshop)
