### ISSUE TITLE
gravacao vindo sozinha como tirar?

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#31]
ontem vc me respondeu mas acho que vc nao entendeu

o produto da banana realmente tem 2 fontes cadastradas

só que eu selecionei a opcao de gravacao interna e nao externa
e fica aparecendo a interna e a externa

eu sou obrigada a selecionar as fontes cadsatradas pq se nao
tem opcao de fonte entendeu?

![Captura de Tela 2021-06-17 às 17 33 14](https://user-images.githubusercontent.com/71886392/122468718-70d34180-cf92-11eb-8f31-1fbb30edd3c9.png)

**Comment by diogenesjup** [comment]
Esse problema já foi resolvido
https://homologacao.servidorseguro.cloud/produto/relogio-splash-banana-lola/
Produto náo aparece a gravação externa (quando marcado no painel que náo é para aparecer)
