### ISSUE TITLE
icones dos status do pedido

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#32]
ta em zip icones dos status do pedido

 o sistema interno, ou seja, no painel
status do cliente é dos e-mails e la dentro do acesso dos pedidos do cliente

**note que:** no [ pedido recebido] que é o primeiro passo tem o [ status do pedido ] o que siginifica que pode estar naqueles status que temos hoje ( status: aguardando / status: pagamento pendente / status: mal sucedido / status: cancelado / ) que siginifica que houve uma tentativa mas não que está pago....

[icones status.zip](https://github.com/diogenesjup/Documentacao-tecnica-BeWatch/files/6678992/icones.status.zip)

![Captura de Tela 2021-06-18 às 16 31 38](https://user-images.githubusercontent.com/71886392/122608503-b5261680-d052-11eb-8245-04a45607f3ed.png)

**Comment by diogenesjup** [comment]
https://homologacao.servidorseguro.cloud/produto/e-os-produtos-pulseiras/
https://homologacao.servidorseguro.cloud/wp-content/themes/bewatch-2021/3d/index.html
