### ISSUE TITLE
[ BUG ]  quando mexe na personalização cai fora no produto

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#33]
acredito que seja um bug
mas eu fui la e troquei o numero da camada e ele sumiu do produto tenho que recadastrar dentro do produto

![Captura de Tela 2021-06-21 às 10 28 56](https://user-images.githubusercontent.com/71886392/122771057-72e01d80-d27c-11eb-8096-954f9e7fd310.png)

**Comment by beprogram** [comment]
pelos meus testes...
tudo o que fica como primeiro
cai fora na personalização
na imagem abaixo ta o ponteiro em primeiro se tu entrar la na customização ele caiu
dai se eu pegar add outro e excluir ele o que ficou em primeiro cai la na customizacao fica como se nao tivesse nada

![Captura de Tela 2021-06-21 às 10 47 59](https://user-images.githubusercontent.com/71886392/122772872-32819f00-d27e-11eb-939b-ed2b1e0fc4fa.png)

**Comment by diogenesjup** [comment]
Problema corigido!
