### ISSUE TITLE
[ BUG ] não consigo mexer nas camadas o default travou ou vem duplo

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#34]
se entrar no customize ta tudo duplicado
[ gato salem ] esse exemplo abaixo

eu vi novamente o teu video e vi que no teu ja tava duplicado assim com esse erro

![Captura de Tela 2021-06-21 às 11 09 33](https://user-images.githubusercontent.com/71886392/122776150-34992d00-d281-11eb-81f1-3f6fe256e931.png)

**Comment by diogenesjup** [comment]
problema resolvido
