### ISSUE TITLE
[ bug ]  fontes da gravacao

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#35]
tanto na fonte externa quando a interna está sempre vindo uma fonte padrão [ que eu n sei qual é ] 
só troca se eu trocar nos ''A''s para trocar a fonte

porém essa fonte padrão não está nos A (fontes) que eu cadastrei

o que vai ser um problema [ que acontece no beloop atual ]  pois se a pessoa não clica em um A vai essa fonte que nao está ali, entendeu?

**Comment by diogenesjup** [comment]
Corrigido, a primeira fonte selecionada sempre será a primeira fonte cadastrada
