### ISSUE TITLE
[ PROGRAMAÇÃO ] como o cliente escolhe o tipo de fonte no besteel?

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#37]
pra mim não aparece a opção de fonte para a gravação externa

pra te ser bem sincera a gravação **externa eu preferia que a gente colocasse lá junto com os ícones e a cor da fonte.
ou seja, onde eu gerencio os icones e a cor da fonte eu tb gerencio qual tipo de fonte eu quero para a gravação lateral.**

pq ao contrário da gravação interna, a externa eu não tenho muita mobilidade na maquina.

resumindo la nas personalizacoes gerais > icones> ter a opcao de subir as fontes que eu quero para  a externa

![Captura de Tela 2021-06-21 às 14 50 12](https://user-images.githubusercontent.com/71886392/122805869-02e38e80-d2a0-11eb-8a48-08b9f0569c41.png)

**Comment by diogenesjup** [comment]
Item feito, enviei e-mail a respeito
