### ISSUE TITLE
[ PROGRAMAÇÃO ] faltou um link 

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#38]
na parte dos banners
são 2 links que precisamos ter

- 1 link que é o do banner ( açao do banner ex.: compre o jeans !!! >>> clica no banner e vai para a categoria jeans) 
- 2 link - clicla naquela frase abaixo e  direciona para as regras da promoção ( se nao tiver regra é so nao por a frase nem o link )

![Captura de Tela 2021-06-21 às 16 35 18](https://user-images.githubusercontent.com/71886392/122818930-26163a00-d2b0-11eb-8006-73cbbe42f8a5.png)

**Comment by diogenesjup** [comment]
Esse já estava corrigido
