### ISSUE TITLE
[ PROGRAMAÇÃO ]  quadrados se ajustarem ao tamanho do texto

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#39]
precisamos que os quadrados sejam do tamanho do texto e não fixo.
isso para TODOS os locais que tiver esses quadrados.
nesse caso é na pulseira extra de silicone

![Captura de Tela 2021-06-22 às 10 48 10](https://user-images.githubusercontent.com/71886392/122936325-72608900-d347-11eb-94b2-dd8f34bb5662.png)

**Comment by diogenesjup** [comment]
Esse já falamos ontem
