### ISSUE TITLE
[ PROGRAMAÇÃO ] - faltou o default dos grupos de personalizações

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#41]
Para os grupos de personalizações esta faltando a opção de escolha default.
pois estão todos indo com o default la do cadastro dos grupos de personalização e eu precis escolher pelo produto, tipo como você fez com a pulseira. entendeu?

![Captura de Tela 2021-06-24 às 14 15 58](https://user-images.githubusercontent.com/71886392/123305654-be056500-d4f6-11eb-80c0-12831d6e06cc.png)

![image](https://user-images.githubusercontent.com/71886392/123305021-01ab9f00-d4f6-11eb-9bea-e4210dc9a9d9.png)

**Comment by diogenesjup** [comment]
Os grupos externos não tem "Default"
lembra que falei que os default sempre precisam ser os itens de personalização internos
