### ISSUE TITLE
Produtos relacionados (aqueles em baixo)

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#42]
nos produtos relacionados, não consigo editar o titulo em azul : onde esta escrito : "aqui promo brinde" , preciso dessa opção de edição.

E outra questão é o valor tem que puxar o valor da pulseira junto, apresentando ao cliente o valor do relógio completo.
![image](https://user-images.githubusercontent.com/71886392/123309338-2d7d5380-d4fb-11eb-9bae-fa14233fb747.png)

**Comment by diogenesjup** [comment]
O título em azul, será adicionado apenas na promoção e náo no produto
