### ISSUE TITLE
remoção de busca - dentro do cadastro - "Produtos relacionados (aqueles em baixo) "

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#43]
ao buscar os itens para relacionar, remover a busca por "tags" , irá tornar muito extenso e ruim de pesquisar.

![image](https://user-images.githubusercontent.com/71886392/123309932-e8a5ec80-d4fb-11eb-8b46-1a07e80b72c4.png)

**Comment by diogenesjup** [comment]
Ajustado
