### ISSUE TITLE
no painel - cadastro de produtos

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#44]
Dentro do painel no cadastro dos produtos, preciso de um filtro para cada tipo de relógio. Por exemplo o da imagem que diz "relogio besplash ....) porque apenas por categoria, não consigo filtrar o tipo do produto. E na necessidade de alterar apenas esse tipo de produto, fico sem possibilidades, visto que a categoria irá apresentar todos os "tipos de relógio"

![image](https://user-images.githubusercontent.com/71886392/123312290-839fc600-d4fe-11eb-9807-94a63b42322a.png)

**Comment by diogenesjup** [comment]
Vocjá podia filtrar por tema como mostrado ontem, porém, adicionei novos filtros para o tipo de produto. Mas atenção por que existem dois: Filtrar por tipos do produto = Tipos do produto WooCommerce, e Tipo de produto BeWatch = Nossos tipos de produtos, como Personalizavel, pulseira etc
