### ISSUE TITLE
[ programação ] camada do gato (produto personalizado) corrigir

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#48]
camada do gato (produto personalizado) corrigir, conforme conversamos na call.
segue imagem

![Captura de Tela 2021-06-28 às 07 59 50](https://user-images.githubusercontent.com/71886392/123629642-e1782a80-d7ea-11eb-9a64-5ca534244600.png)

**Comment by diogenesjup** [comment]
Corrigido
