### ISSUE TITLE
[P/ ROBERTA] Qual a mensagem oficial/final para instrução dos angulos e posições?

### ISSUE THREAD

**Issue by diogenesjup** [diogenesjup/BeWatch#5]
Qual a mensagem oficial/final para instrução dos angulos e posições?

![Captura de Tela 2021-06-07 às 21 40 49](https://user-images.githubusercontent.com/3137920/121104890-569ea400-c7d9-11eb-88a3-d5b60f82947c.png)

**Comment by beprogram** [comment]
mandei no e-mail ..\\''respostas do e-mail DO VIDEO''// é bom dar uma olhada nesse e-mail

e a frase é:
mova o seu texto na posição que  você preferir

**Comment by beprogram** [comment]
deixar a frase aberta no painel
