### ISSUE TITLE
PROBLEMA  - ITENS RELACIONADOS

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#50]
Vou explicar ,assim entendemos a função, para que possamos chegar a uma melhor performance. Os produtos cadastrados nos relacionados, servem para mostrar ao cliente de que se ele optou por uma estampa de bananas nos relacionados deverá aparecer estampas como morango, abacaxi, maça e assim por diante. Porem a manutenção dessa regra, não pode ser em : tem que entrar em cada produto cadastrado e fazer a vinculação manual. Pois o trabalho empenhado alem de gigante ao fazer o lançamento de uma nova estampa laranja por exemplo teremos que entrar em todas os produtos para colocar o novo "relacionado"( laranja). Portanto a sugestao é ter no painel o campo "RELACIONADO" dentro desse campo puxar todas as categorias e seus produtos, para que o que se faz dentro do produto eu faca dentro do painel, não havendo a necessidade de entrar em cada produto para fazer as alterações. Desta forma a manutenção de atualização com novas estampas fica viável. 

Bem como se faz necessário a colocação no painel para os "MAIS VENDIDOS" e as "NOVIDADES" pois ter que entrar em cada produto cadastrado para vincular na categoria não é viável. Preciso dentro do painel esse campo e dentro do campo puxar todas os produtos, por categorias como uma mapa. Com a proposta de selecionar o que quero que vá para essas "MAIS VENDIDOS e NOVIDADES" dentro do painel sem ter que entrar em cada produto.

**Comment by diogenesjup** [comment]
Acredito que esse item foi corrigido com a função dos temas
