### ISSUE TITLE
por as flechinhas [ produto personalizado ] [personalizacao]

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#51]
achei que ficou meio dificil de entender que tem que puxar com o mouse...
que de para clicar com as flechas tb.. 

![Captura de Tela 2021-07-03 às 09 19 26](https://user-images.githubusercontent.com/71886392/124353938-d739a000-dbdf-11eb-8439-3f48562ed251.png)

**Comment by diogenesjup** [comment]
Corrigido
