### ISSUE TITLE
[PROGRAMACAO] Não troca a frase quando vai direto digitar  o nome 

### ISSUE THREAD

**Issue by beprogram** [diogenesjup/BeWatch#55]
Não troca a frase quando vai direto digitar  o nome 
só se ficar clicando la em cima, se nao nao puxa automatico junto com a segunda imagem!!!

https://user-images.githubusercontent.com/71886392/124646171-b20c9200-de6a-11eb-8240-249dcba59cb8.mov

**Comment by diogenesjup** [comment]
Ja corrigido
